logging:
  level:
    krud: DEBUG


spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//kfosdevdb_vip.koreanair.com:2003/OPERAT
    username: kfos
    password: fosk2117
