logging:
  level:
    krud: DEBUG
    com.zaxxer.hikari: DEBUG


spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//${db.host}:${db.port}/${db.schema}
    username: ${db.user}
    password: ${db.password}

editConfig:
  schema: ${schema}
  packageName: c${package}

